# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ECE/428/Lab/project_1/project_1.srcs/sources_1/ip/sigmoid_0_2/sigmoid_0.xci
# IP: The module: 'sigmoid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ECE/428/Lab/project_1/project_1.srcs/sources_1/ip/sigmoid_0_2/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sigmoid_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/ECE/428/Lab/project_1/project_1.srcs/sources_1/ip/sigmoid_0_2/sigmoid_0.xci
# IP: The module: 'sigmoid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ECE/428/Lab/project_1/project_1.srcs/sources_1/ip/sigmoid_0_2/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sigmoid_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
